# Generated by Django 3.1 on 2020-09-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Item',
        ),
    ]
